### ISSUE TITLE
Treinamento de Git

### ISSUE THREAD

**Issue by mendesiasmin** [fga-eps-mds/RecomendaFGA#2]
[Tutorial Básico](http://rogerdudler.github.io/git-guide/index.pt_BR.html)

- [x] git init
- [x] git clone
- [x] git add
- [ ] git diff
- [x] git commit
- [x] git push
- [ ] Conflitos
- [ ] git pull
- [ ] git merge
- [x] git log
- [ ] git rebase
- [ ] git reset
- [ ] git fetch
- [ ] git remote

- [ ]  Criar uma branch
- [ ] Atualizar branch com a master
- [ ] Pull Request

**Comment by zarbielli** [comment]
Presente

**Comment by GabrielDVpereira** [comment]
https://services.github.com/on-demand/downloads/pt_BR/github-git-cheat-sheet.pdf

**Comment by WeillerFernandes** [comment]
git log apresenta o histórico de commits;

**Comment by zarbielli** [comment]
git rebase -i --root 
Muda a mensagem do commit

**Comment by GabrielDVpereira** [comment]
problema: conflito de merge/pull request 
-git status // analisar o documento alterado que esta gerando o problema de pull 
-git checkout <documento_com_problema>// limpa as alterções no arquivo
-git pull --rebase

**Comment by Ridersk** [comment]
Como pegar todas as branchs do repositório remoto para o local? Não apenas a branch padrão.
